name: network_sharing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  flutter_svg: ^2.0.9
  process_runner: ^4.2.0
  toast: ^0.3.0
  icons_launcher: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
icons_launcher:
    image_path: "assets/images/app_logo.png"
    platforms:
      android:
        enable: true
      ios:
        enable: true
flutter:
  uses-material-design: true

  assets:
    - assets/images/
